###下面三个参数暂时不要修改
region_id ="cn-hangzhou"
page_number ="1"
page_size = "100"

##替换成自己的key和secret
access_key = ""
access_secret =""

##更新频率,单位是秒
update_interval = 60
##记录类型
type ="A"
##主机记录,如果要解析@.example.com,要填写@,而不是空
rr = "wkm2"
##一级域名
domain_name ="example.com"
##TTL值
ttl = "600"

##获取最新WAN口ip命令,为空时,启用下面四个参数来获取ip
new_ip_command="curl -s whatismyip.akamai.com"
# or
# new_ip_command="curl -s myip.ipip.net | perl -lne 'print $1 if /((\d+\.){3}\d+)/'"

##当new_ip_command为空时,使用下面四个参数来获取ip
###调用http GET方法从new_ip_source获取输出
##不要忘记前面的http或者https
new_ip_source ="http://myip.ipip.net"
###把GET方法获取的输出用下面的正则匹配
filter_ip_regex ="([0-9]+\\.){3}[0-9]+"
###master_index和slave_index是作为regexp.FindAllStringSubmatch返回的[][]string的两个下标
###从匹配到正则中选取第master_index个数组
master_index=0
###选取第master_index个数组中第slave_index元素作为ip
slave_index=0
